### ISSUE TITLE
Command line interface?

### ISSUE THREAD

**Issue by trishmapow** [paulgclark/waveconverter#6]
I understand that this uses GNURadio blocks to process the data, in python files. How could you use the shell to automate the demod and decode stages given an IQ file and protocol?

**Comment by paulgclark** [comment]
You are correct, I do call gnuradio APIs from python to do the RF processing.

To build a script to automate this, you would simply call waveconverter from the command line using the iq file name and a previously defined protocol, making sure to leave off the -g flag (which brings up the gui):
./waveconverter.py -q <iq file name> -p <protocol number>

You can also supply your own signal frequency if you want to override the frequency provided by the protocol. This could be important because some cheap designs have wildly varying transmit frequencies from one individual device to the next. 

The trick is to do automatically find that new frequency, and for that you'd either need to do a brute force search (sweep the provided input frequency across the iq file's frequency range) or write something clever to find the signal. You could give wavefinder (also in my github) a try if you want to do the latter, but it's still in a crude development state.

Hope this helps.

**Comment by trishmapow** [comment]
Thanks a lot, luckily the key fob I have stays on one frequency.

**Comment by paulgclark** [comment]
Cool. Good luck with the fob.
